export const categoryFilters = [
  'Frontend',
  'Backend',
  'Full-Stack',
  'Mobile',
  'UI/UX',
  'Game Dev',
  'DevOps',
  'Data Science',
  'Machine Learning',
  'Cybersecurity',
  'Blockchain',
  'E-commerce',
  'Chatbots',
];

export const keywords = [
  'Codefolio',
  'Developer Portfolio',
  'Developer Showcase',
  'Coding Projects',
  'Code Projects',
  'Web Development Showcase',
  'Next.js Portfolio',
  'Developer Poster Gallery',
  'Project Categorization',
  'Coding Community',
  'Digital Footprint',
  'Showcasing Code Projects',
  'Developer Creativity',
  'Code Gallery',
  'Developer Work Showcase',
  'Tech Portfolio',
  'Creative Coding Projects',
  'Dribbble for Developers',
  'Code Portfolio Website',
  'Developer Network',
];
